name: Wordle Clone
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Wordle web and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version:'2.10.0'
          channel: 'stable'
      - run: flutter build web --release